In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

file_name = rf'/content/drive/My Drive/Datasets/accepted_2007_to_2018Q4 cleaned.csv'
loan_data_df = pd.read_csv(file_name)

In [ ]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Collecting pandas
  Downloading pandas-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 90.0 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 43.7 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.1.3 which is incompatible.
Successfully installed pandas-2.1.3 tzdata-2023.3

In [ ]:
loan_data_df.head(10)

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,open_il_12m,num_actv_bc_tl,delinq_2yrs,inq_last_12m,mths_since_last_delinq_category,mths_since_last_delinq,last_fico_range_low,mort_acc,days_since_issue_d,days_since_last_cred_pull
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,0-2,2-5,0-2,2-5,20-50,Recent,Poor,0-2,2902,1716
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,0-2,5-10,0-2,5-10,0-20,Very Recent,Average,2-5,2902,1716
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,0-2,2-5,0-2,0-2,NaN,Never,Good,5-10,2902,1716
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,0-2,2-5,0-2,0-2,NaN,Never,Average,0-2,2902,1716
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,0-2,2-5,0-2,2-5,0-20,Very Recent,Good,5-10,2902,2081
5,68426831,11950.0,36 months,2015-12-01,405.18,13.44,C,C3,12798.0,n,...,0-2,2-5,0-2,0-2,NaN,Never,Good,0-2,2902,2385
6,68476668,20000.0,36 months,2015-12-01,637.58,9.17,B,B2,360358.0,n,...,0-2,2-5,0-2,0-2,20-50,Recent,Average,2-5,2902,1716
7,67275481,20000.0,36 months,2015-12-01,631.26,8.49,B,B1,141601.0,n,...,0-2,2-5,0-2,2-5,0-20,Very Recent,Average,2-5,2902,1716
8,68466926,10000.0,36 months,2015-12-01,306.45,6.49,A,A2,27957.0,n,...,0-2,5-10,0-2,0-2,NaN,Never,Good,0-2,2902,1716
9,68616873,8000.0,36 months,2015-12-01,263.74,11.48,B,B5,199696.0,n,...,2-5,2-5,0-2,0-2,50+,Old,Average,0-2,2902,1836

In [ ]:
print(loan_data_df['purpose'].unique())

['debt_consolidation' 'other' 'house' 'credit_card' 'car']

**Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
loan_data_df['grade'] = label_encoder.fit_transform(loan_data_df['grade'])
loan_data_df['sub_grade'] = label_encoder.fit_transform(loan_data_df['sub_grade'])
loan_data_df['emp_length'] = label_encoder.fit_transform(loan_data_df['emp_length'])
loan_data_df['delinq_2yrs'] = label_encoder.fit_transform(loan_data_df['delinq_2yrs'])
loan_data_df['inq_last_12m'] = label_encoder.fit_transform(loan_data_df['inq_last_12m'])
loan_data_df['last_fico_range_low'] = label_encoder.fit_transform(loan_data_df['last_fico_range_low'])
loan_data_df['mort_acc'] = label_encoder.fit_transform(loan_data_df['mort_acc'])
loan_data_df['mths_since_last_delinq'] = label_encoder.fit_transform(loan_data_df['mths_since_last_delinq'])
loan_data_df['num_actv_bc_tl'] = label_encoder.fit_transform(loan_data_df['num_actv_bc_tl'])
loan_data_df['open_il_12m'] = label_encoder.fit_transform(loan_data_df['open_il_12m'])
loan_data_df['total_acc'] = label_encoder.fit_transform(loan_data_df['total_acc'])
loan_data_df.head()

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,sub_grade_numerical,emp_length_numerical,delinq_2yrs_numerical,inq_last_12m_numerical,last_fico_range_low_numerical,mort_acc_numerical,mths_since_last_delinq_numerical,num_actv_bc_tl_numerical,open_il_12m_numerical,total_acc_numerical
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,13,0,0,2,4,0,2,2,0,1
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,10,0,0,4,0,2,3,4,0,3
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,8,0,0,0,2,3,0,2,0,1
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,14,0,0,0,0,0,0,2,0,1
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,25,3,0,2,2,3,3,2,0,3

**Binary Label Encoding**

In [ ]:
loan_data_df['term_'] = label_encoder.fit_transform(loan_data_df['term'])
loan_data_df['pymnt_plan'] = label_encoder.fit_transform(loan_data_df['pymnt_plan'])
loan_data_df['loan_status'] = label_encoder.fit_transform(loan_data_df['loan_status'])
loan_data_df.head()

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,inq_last_12m_numerical,last_fico_range_low_numerical,mort_acc_numerical,mths_since_last_delinq_numerical,num_actv_bc_tl_numerical,open_il_12m_numerical,total_acc_numerical,term_binary,pymnt_plan_binary,loan_status_binary
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,2,4,0,2,2,0,1,0,0,1
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,4,0,2,3,4,0,3,0,0,1
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,0,2,3,0,2,0,1,1,0,1
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,0,0,0,0,2,0,1,1,0,1
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,2,2,3,3,2,0,3,1,0,1

**Normalization**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
loan_data_df['loan_amnt'] = scaler.fit_transform(loan_data_df[['loan_amnt']])
loan_data_df['days_since_issue_d'] = scaler.fit_transform(loan_data_df[['days_since_issue_d']])
loan_data_df['installment'] = scaler.fit_transform(loan_data_df[['installment']])
loan_data_df['int_rate'] = scaler.fit_transform(loan_data_df[['int_rate']])
loan_data_df['tot_cur_bal'] = scaler.fit_transform(loan_data_df[['tot_cur_bal']])
loan_data_df['total_rec_int'] = scaler.fit_transform(loan_data_df[['total_rec_int']])
loan_data_df['total_rec_late_fee'] = scaler.fit_transform(loan_data_df[['total_rec_late_fee']])
loan_data_df['total_rec_prncp'] = scaler.fit_transform(loan_data_df[['total_rec_prncp']])
loan_data_df['out_prncp'] = scaler.fit_transform(loan_data_df[['out_prncp']])
loan_data_df['annual_inc'] = scaler.fit_transform(loan_data_df[['annual_inc']])
loan_data_df['tot_hi_cred_lim'] = scaler.fit_transform(loan_data_df[['tot_hi_cred_lim']])
loan_data_df['days_since_last_cred_pull'] = scaler.fit_transform(loan_data_df[['days_since_last_cred_pull']])
loan_data_df.head()

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,installment_normalized,int_rate_normalized,tot_cur_bal_normalized,total_rec_int_normalized,total_rec_late_fee_normalized,total_rec_prncp_normalized,out_prncp_normalized,annual_inc_normalized,tot_hi_cred_lim_normalized,days_since_last_cred_pull_normalized
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,0.068867,0.338006,0.014532,0.029147,6.400151e-12,0.090000,0.000000,0.000500,0.017805,0.012736
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,0.475450,0.260125,0.020498,0.034749,6.400151e-12,0.617500,0.000000,0.000591,0.031402,0.012736
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,0.249420,0.213006,0.019024,0.095980,6.400151e-12,0.500000,0.000000,0.000573,0.021842,0.012736
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,0.481060,0.371495,0.030236,0.438473,6.400151e-12,0.477559,0.397441,0.001000,0.038122,0.012736
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,0.166179,0.667445,0.033267,0.047548,6.400151e-12,0.260000,0.000000,0.000949,0.043957,0.162695

**One Hot Encoding**

In [ ]:
purpose_encoded = pd.get_dummies(loan_data_df['purpose'], prefix='purpose')
home_ownership_encoded = pd.get_dummies(loan_data_df['home_ownership'], prefix='ownership')
loan_data_df = pd.concat([loan_data_df, purpose_encoded, home_ownership_encoded], axis=1)
loan_data_df.head()

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_house,purpose_other,ownership_MORTGAGE,ownership_NONE,ownership_OTHER,ownership_OWN,ownership_RENT
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,0,0,1,0,0,1,0,0,0,0
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,0,0,0,0,1,1,0,0,0,0
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,0,0,0,1,0,1,0,0,0,0
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,0,0,1,0,0,1,0,0,0,0
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,0,0,0,1,0,1,0,0,0,0

**Target Encoding**

In [ ]:
column_to_encode_addr = 'addr_state'
mean_encoding_addr = loan_data_df.groupby(column_to_encode_addr)['loan_status_binary'].mean()
loan_data_df[f'{column_to_encode_addr}_encoded'] = loan_data_df[column_to_encode_addr].map(mean_encoding_addr)
column_to_encode_emp_title = 'emp_title'
mean_encoding_emp_title = loan_data_df.groupby(column_to_encode_emp_title)['loan_status_binary'].mean()
loan_data_df[f'{column_to_encode_emp_title}_encoded'] = loan_data_df[column_to_encode_emp_title].map(mean_encoding_emp_title)
loan_data_df.head()

,id,loan_amnt,term,issue_d,installment,int_rate,grade,sub_grade,tot_cur_bal,pymnt_plan,...,purpose_debt_consolidation,purpose_house,purpose_other,ownership_MORTGAGE,ownership_NONE,ownership_OTHER,ownership_OWN,ownership_RENT,addr_state_encoded,emp_title_encoded
0,68407277,3600.0,36 months,2015-12-01,123.03,13.99,C,C4,144904.0,n,...,1,0,0,1,0,0,0,0,0.863471,0.875000
1,68355089,24700.0,36 months,2015-12-01,820.28,11.99,C,C1,204396.0,n,...,0,0,1,1,0,0,0,0,0.860412,0.896467
2,68341763,20000.0,60 months,2015-12-01,432.66,10.78,B,B4,189699.0,n,...,0,1,0,1,0,0,0,0,0.886498,0.801921
3,66310712,35000.0,60 months,2015-12-01,829.90,14.85,C,C5,301500.0,n,...,1,0,0,1,0,0,0,0,0.864474,0.800000
4,68476807,10400.0,60 months,2015-12-01,289.91,22.45,F,F1,331730.0,n,...,0,1,0,1,0,0,0,0,0.863471,0.877339

**Exporting dataframe as csv file for modeling**

In [ ]:
loan_data_df.to_csv('/content/drive/My Drive/Datasets/accepted_2007_to_2018Q4 cleaned encoded.csv', index=False)

NameError: ignored